### PR TITLE
Gnome 3.34 compatibility

### PR DESCRIPTION
**Pull request by Silarn**
This includes a number of changes from 3.32 compatibility. In addition:

- PopupMenuItem and PopupSubmenuItem were converted to GObjects upstream
  - Updated class definitions
  - Added Signals definitions
  - Had to rework event parameters as there wasn't an obvious way to use a JS Object inside a GObject signal
- A few small tweaks

### CODE REVIEW

**Comment by Silarn** [comment]
I went ahead and converted those signals to use GLib Variant types, which is about as close as you can get to passing a JS Object through a GObject. It uses the a{sv} signature, which is an array of string -> variant libraries. There's unfortunately no way to just pass in an Object to the Variant constructor, but as of 3.34 there's a recursiveUnpack() function which takes the Variant and recursively converts it back into the expected object/array.

I suppose there was nothing wrong with breaking up the event Object into separate Signal/handler parameters, but I'm trying to keep the core logic of the extension as close as possible to the original.

**Comment by fffilo** [comment]
I merged your branch and fix conflicts (you can try `features/es6` branch), but I can not make this work. I am using gnome shell 3.34.1 at Ubuntu 19.10.

    GObject.registerClass() used with invalid base class (is Machine)
    registerClass@resource:///org/gnome/gjs/modules/overrides/GObject.js:85:15
    @/home/fffilo/.local/share/gnome-shell/extensions/gnome-vagrant-indicator@gnome-shell-exstensions.fffilo.github.com/menu.js:433:12

It seams I can not register gobject class while extending PopupMenuItem. If I try this:

    const { St, Gio, GObject } = imports.gi;
    const PopupMenu = imports.ui.popupMenu;
    var Foo = GObject.registerClass(class Bar extends PopupMenu.PopupSubMenu {});

...I get:

    TypeError: GObject.registerClass() used with invalid base class (is PopupSubMenu)

...which is very strange, cuz extending (for example) PopupMenuItem works.

**Comment by Silarn** [comment]
I'll take a look. I'm personally using Fedora 31 with Gnome 3.34.3. It's possible there's a difference, I suppose.

**Comment by Silarn** [comment]
There are some differences between the es6 branch and my branch, Path is directly extending PopupSubMenuMenuItem and not Machine. Since Machine is not currently registered as a GObject, this will fail. Let me see if I can merge the es6 branch and sort it out.

**Pull request merged**
